/**
 * Public-surface scan.
 *
 * Every name a `@pixen/*` package exports is a contract, and CLAUDE.md is
 * explicit that changing one is a decision rather than cleanup. The trouble is
 * that most of them are not decided at all: a barrel that says `export *` hands
 * the public API whatever the folder happens to contain, so adding a file to
 * `viewport/` published its contents, and nobody had to agree to it.
 *
 * This changes nothing about what is exported. It writes the surface down, in
 * `docs/PUBLIC-API.md`, and fails when the code and that file disagree. Adding
 * a name is then a line in a reviewed diff instead of a side effect, and
 * removing one cannot happen by accident at all.
 *
 * Read from source rather than from `dist`, like every other scan here, so it
 * runs on a fresh clone and reports on what is written rather than on what was
 * last built.
 */
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

/** The packages that publish. `apps/*` are demos and are not a contract. */
const PACKAGES = ["core", "web", "react", "vue", "svelte", "video"];

const RECORD = "docs/PUBLIC-API.md";

/** `export * from "./x.js"` — everything the named module exports. */
const STAR = /^export \* from ["'](\.[^"']+)["'];?$/gm;
/** `export * as ns from "./x.js"` — one name, whatever the module holds. */
const NAMESPACE = /^export \* as (\w+) from ["'][^"']+["'];?$/gm;
/**
 * `export { a, b as c, type D } from "./x.js"`, the `export type { … }` form,
 * and both again without a `from` — a local re-export. A specifier that is not
 * relative is another package's name being republished under ours, which is
 * every bit as much a contract as one of our own.
 */
const NAMED = /^export (?:type )?\{([^}]*)\}(?:\s+from\s+["'][^"']+["'])?;?$/gms;
/** `export default X` — one contract, under the name an importer sees. */
const DEFAULT = /^export default \w+;?$/m;
/** A declaration exported where it is written. */
const DECLARED = /^export (?:declare )?(?:async )?(?:function|const|let|class|interface|type|enum) (\w+)/gm;

function resolve(from, specifier) {
  const base = from.slice(0, from.lastIndexOf("/"));
  const parts = `${base}/${specifier.replace(/\.js$/, "")}`.split("/");
  const path = [];
  for (const part of parts) {
    if (part === ".") continue;
    else if (part === "..") path.pop();
    else path.push(part);
  }
  return path.join("/");
}

/**
 * The names a module publishes, following re-exports through the source.
 *
 * `seen` stops a cycle from recursing forever; a module already being walked
 * contributes nothing new, because whatever it re-exports is already on its way
 * up from the walk that reached it.
 */
function exportsOf(path, read, seen = new Set()) {
  if (seen.has(path)) return new Set();
  seen.add(path);

  const source = read(`${path}.ts`) ?? read(`${path}/index.ts`) ?? read(`${path}.tsx`);
  if (source == null) return new Set();
  const here = source.file;
  const names = new Set();

  for (const match of source.text.matchAll(DECLARED)) names.add(match[1]);

  for (const match of source.text.matchAll(NAMED)) {
    for (const raw of match[1].split(",")) {
      const clause = raw.replace(/^\s*type\s+/, "").trim();
      if (!clause) continue;
      const alias = clause.split(/\s+as\s+/);
      names.add((alias[1] ?? alias[0]).trim());
    }
  }

  for (const match of source.text.matchAll(NAMESPACE)) names.add(match[1]);

  if (DEFAULT.test(source.text)) names.add("default");

  for (const match of source.text.matchAll(STAR)) {
    for (const name of exportsOf(resolve(here, match[1]), read, seen)) names.add(name);
  }

  return names;
}

export function scanPublicSurface(root = process.cwd()) {
  // `--others --exclude-standard` as well as the index: a file that has not
  // been added yet is exactly the one this scan exists to notice, and reading
  // only what git already tracks would report clean on it.
  const tracked = execFileSync("git", ["ls-files", "-z", "--cached", "--others", "--exclude-standard"], {
    cwd: root,
    encoding: "utf8",
  })
    .split("\0")
    .filter((file) => /\.tsx?$/.test(file));

  const contents = new Map();
  for (const file of tracked) {
    try {
      contents.set(file, readFileSync(`${root}/${file}`, "utf8"));
    } catch {
      // Listed but unreadable: it cannot contribute an export worth recording.
    }
  }
  const read = (file) => (contents.has(file) ? { file, text: contents.get(file) } : null);

  const surface = new Map();
  for (const name of PACKAGES) {
    surface.set(name, [...exportsOf(`packages/${name}/src/index`, read)].sort());
  }
  return surface;
}

export function renderRecord(surface) {
  const lines = [
    "# Public API",
    "",
    "Every name each `@pixen/*` package exports. Generated by",
    "`pnpm check:surface --write`; `pnpm check:surface` fails when it and the",
    "code disagree.",
    "",
    "This is a record, not a decision: a name being here means it is reachable,",
    "not that it was meant to be. What it buys is that adding one shows up in a",
    "reviewed diff rather than arriving as a side effect of a barrel — see",
    "`scripts/public-surface.mjs` for what went wrong without it.",
    "",
  ];
  for (const [name, names] of surface) {
    lines.push(`## @pixen/${name}`, "", `${names.length} names.`, "", "```");
    lines.push(...names);
    lines.push("```", "");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function compare(surface, recorded) {
  const findings = [];
  for (const [name, names] of surface) {
    const before = recorded.get(name) ?? [];
    const added = names.filter((n) => !before.includes(n));
    const removed = before.filter((n) => !names.includes(n));
    if (added.length || removed.length) findings.push({ package: name, added, removed });
  }
  return findings;
}

export function parseRecord(text) {
  const recorded = new Map();
  for (const match of text.matchAll(/^## @pixen\/(\S+)\n\n\d+ names\.\n\n```\n([\s\S]*?)```/gm)) {
    recorded.set(match[1], match[2].trim().split("\n").filter(Boolean));
  }
  return recorded;
}

export function report(findings) {
  if (findings.length === 0) return "public-surface scan: clean";
  const lines = [];
  for (const finding of findings) {
    lines.push(`@pixen/${finding.package}:`);
    for (const name of finding.added) lines.push(`  + ${name}`);
    for (const name of finding.removed) lines.push(`  - ${name}`);
  }
  lines.push(
    "",
    `The published API and ${RECORD} disagree. If the change was meant, run`,
    "`pnpm check:surface --write` and let the diff be reviewed with the rest.",
  );
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const surface = scanPublicSurface();
  if (process.argv.includes("--write")) {
    const { writeFileSync } = await import("node:fs");
    writeFileSync(RECORD, renderRecord(surface));
    console.log(`wrote ${RECORD}`);
  } else {
    let recorded = new Map();
    try {
      recorded = parseRecord(readFileSync(RECORD, "utf8"));
    } catch {
      // No record yet: everything reads as added, which is the right first run.
    }
    const findings = compare(surface, recorded);
    console.log(report(findings));
    if (findings.length > 0) process.exitCode = 1;
  }
}
